//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Leave
    {
        [Required]
        public long LeaveID { get; set; }
        [Required]
        public string ID { get; set; }
        [Required]
        [DisplayName("Description Of Leave")]
        public string LeaveDescription { get; set; }
        [DisplayName("Temp Contact")]
        public string TempContact { get; set; }
        [Required]
        [DisplayName("Start Date")]
        public System.DateTime StartDate { get; set; }
        [Required]
        [DisplayName("End Date")]
        public System.DateTime EndDate { get; set; }
        [Required]
        [DisplayName("Leave Type")]
        public string LeaveType { get; set; }
        public short LeaveTypeCount { get; set; }
        public short TotalLeaveCount { get; set; }

        public virtual Teacher Teacher { get; set; }
    }
}
