//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Leaves = new HashSet<Leave>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int Designation_Id { get; set; }
        public string Pan { get; set; }
        public Nullable<decimal> Aadhar { get; set; }
        public Nullable<decimal> Phno { get; set; }
        public byte[] Fingerprint { get; set; }
        public int Dept_Id { get; set; }
        public string Qualification { get; set; }
        public string Pub_No { get; set; }
        public string Prev_Exp { get; set; }
        public string Events { get; set; }
        public int Project_Id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
    }
}
